# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------
# the main title
title: "@Okie_Chase"

# it will display as the sub-title
tagline: Personal blog under construction.

# used by seo meta and the atom feed
description: >-
  "Personal blog of Chase Dickinson built using Chirpy theme for Jekyll and deployed on GitHub Pages."

# fill in the base hostname & protocol for your site, e.g., 'https://username.github.io'
url: "https://ChaseDickinson.github.io"

# change to your full name
author: Chase Dickinson

# support internet resources
avatar: /assets/img/profile.jpg

# change to your linkedin username
linkedin:
  username: chaseadickinson

# change to your github username
github:
  username: chasedickinson

# change to your twitter username
twitter:
  username: okie_chase

# change to your instagram username
instagram:
  username: okie_chase

social:
  # it will shows as the copyright owner in Footer
  name: Chase Dickinson
  # change to your email address
  #email: example@doamin.com
  links:
    # The first element serves as the copyright owner's link
    # change to your linkedin homepage
    - https://linkedin.com/in/chaseadickinson
    # change to your github homepage
    - https://github.com/chasedickinson
    # change to your twitter homepage
    - https://twitter.com/okie_chase
    # change to your instagram homepage
    - https://instagram.com/okie_chase/

# change to your verification string
#google_site_verification: google_meta_tag_verification
#--------------------------


# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/Chicago

google_analytics:
  # Fill with your Google Analytics ID
  id: ''
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: ''
    # pv data local cache, good for the users from GFW area.
    cache: false

disqus:
  # boolean type, the global switch for posts comments.
  comments: false
  # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  shortname: ''

# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dark

# boolean type, the global switch for ToC in posts.
toc: true

paginate: 10

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# or you think you're smart enough to change other relevant URLs within this template.
permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      # An empty string here means all files in the project
      path: ''
      type: posts
    values:
      layout: post
      # Enable comments in posts.
      comments: true
      # Display TOC column in posts.
      toc: true
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: index.html
    values:
      breadcrumb:
        -
          label: Posts
  -
    scope:
      path: tags
    values:
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: ''
      # see `site.collections`
      type: tabs
    values:
      layout: page
      # Hide title in mobile screens.
      dynamic_title: true
      breadcrumb:
        -
          label: Home
          url: /

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM.
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

# see: <https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md>
jekyll-archives:  
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'
#jekyll-archives:  
#  enabled: [tags]
#  layouts:
#    tag: tag
#  permalinks:
#    tag: '/tags/:name/'
